### ISSUE TITLE
Where do you put the .htmllintrc file for sublime?

### ISSUE THREAD

**Issue by mmmarklu** [necramirez/SublimeLinter-contrib-htmllint#1]

**Comment by necramirez** [comment]
Haven't checked recently, but it should work if you place it in your project root.

**Comment by saadq** [comment]
I seem to be having the same issue. I put my `.htmllintrc` file in my project root and still got a message that says 

    SublimeLinter: WARNING: no htmllint version could be extracted from:
    local .htmllintrc file not found (you can create one using "htmllint init")

I tried making another one in my home (`~`) folder, which didn't help either.

**Comment by necramirez** [comment]
Strange. I just checked, and it could load my `.htmllintrc` from project root...

**Comment by saadq** [comment]
Actually, I just realized I'm having an issue with another linter I use, so it's very possible that I'm having a problem unrelated to your package. Thanks for the quick reply though.

**Comment by nwoltman** [comment]
I have the same problem. I'm on Windows and it's trying to use my `%APPDATA%/npm` folder as the CWD instead of the project root (probably because global npm packages get installed into that folder).

This can be fixed by using SublimeLinter's [NodeLinter subclass](https://github.com/SublimeLinter/SublimeLinter3/blob/master/lint/node_linter.py).

@necramirez Are you willing to make this change or would you accept a PR?

**Comment by necramirez** [comment]
PR would be appreciated, as I don't have the time to make the change myself. 😁
